
sudo: required

services:
  - docker

before_install:
  - docker build . -t build 

#to run the test

script:
#  - docker run -v $(pwd):/app build pytest -v .
  - docker run -v %cd%:/app build pytest -v .